### PR TITLE
Fixed rbac rules to work with OpenShift

### PR DESCRIPTION
**Pull request by hfwen0502**

### CODE REVIEW

**Comment by adrienjt** [comment]
Thank you. Please sign off your commit: https://github.com/admiraltyio/admiralty/blob/master/CONTRIBUTING.md#dco-sign-off

**Comment by hfwen0502** [comment]
Done. Just signed off the commit. Thanks!

**Review by adrienjt — APPROVED** [review]
Thank you.

**Comment by adrienjt** [comment]
Hi @hfwen0502, if you'd like to appear as a [contributor](https://github.com/admiraltyio/admiralty/graphs/contributors) of this repo, please add the email that is associated with your commit (hfwen@us.ibm.com) to your GitHub profile: https://github.com/settings/emails (as explained [here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile#your-local-git-commit-email-isnt-connected-to-your-account)).

**Pull request merged**
